/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hu.modeldriven.astah.easydiagram.ui;

/**
 *
 * @author zsolt
 */
public class AbstractEasyDiagramPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public AbstractEasyDiagramPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        alignmentPanel = new javax.swing.JPanel();
        locationPanel = new javax.swing.JPanel();
        leftLabel = new javax.swing.JLabel();
        leftInputField = new javax.swing.JTextField();
        topLabel = new javax.swing.JLabel();
        topInputField = new javax.swing.JTextField();
        widthLabel = new javax.swing.JLabel();
        widthInputField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        heightInputField = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        otherPanel = new javax.swing.JPanel();
        snapSelectedElementsToPixelButton = new javax.swing.JButton();
        snapDiagramToPixelButton = new javax.swing.JButton();
        straightenLineButton = new javax.swing.JButton();
        saveRestoreButton = new javax.swing.JButton();
        horizontalCenterAlignButton = new javax.swing.JButton();
        verticalCenterAlignButton = new javax.swing.JButton();
        resetItemFlowButton = new javax.swing.JButton();
        fieldPanel = new javax.swing.JPanel();
        valueNameLabel = new javax.swing.JLabel();
        valueNameInputField = new javax.swing.JTextField();
        valueTypeLabel = new javax.swing.JLabel();
        valueTypeInputField = new javax.swing.JTextField();
        createValueButton = new javax.swing.JButton();
        autosavePanel = new javax.swing.JPanel();
        timerLabel = new javax.swing.JLabel();
        timerInputField = new javax.swing.JTextField();
        setTimerButton = new javax.swing.JButton();
        activityPanel = new javax.swing.JPanel();
        unmarshallInputButton = new javax.swing.JButton();
        unmarshallOutputButton = new javax.swing.JButton();
        splitObjectFlowButton = new javax.swing.JButton();
        miscPanel = new javax.swing.JPanel();
        statisticsButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        alignmentPanel.setLayout(new javax.swing.BoxLayout(alignmentPanel, javax.swing.BoxLayout.PAGE_AXIS));

        locationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Location")); // NOI18N

        leftLabel.setText("Left (X):");

        topLabel.setText("Top (Y):");

        widthLabel.setText("Width:");

        heightLabel.setText("Height:");

        applyButton.setText("Apply");

        javax.swing.GroupLayout locationPanelLayout = new javax.swing.GroupLayout(locationPanel);
        locationPanel.setLayout(locationPanelLayout);
        locationPanelLayout.setHorizontalGroup(
            locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(locationPanelLayout.createSequentialGroup()
                        .addComponent(leftLabel)
                        .addGap(18, 18, 18)
                        .addComponent(leftInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(locationPanelLayout.createSequentialGroup()
                        .addComponent(topLabel)
                        .addGap(18, 18, 18)
                        .addComponent(topInputField))
                    .addGroup(locationPanelLayout.createSequentialGroup()
                        .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthLabel)
                            .addComponent(heightLabel))
                        .addGap(18, 18, 18)
                        .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthInputField)
                            .addComponent(heightInputField)))
                    .addComponent(applyButton))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        locationPanelLayout.setVerticalGroup(
            locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftLabel)
                    .addComponent(leftInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topLabel)
                    .addComponent(topInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthLabel)
                    .addComponent(widthInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alignmentPanel.add(locationPanel);

        otherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Others")); // NOI18N

        snapSelectedElementsToPixelButton.setText("Snap selected to pixel");
        snapSelectedElementsToPixelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapSelectedElementsToPixelButtonActionPerformed(evt);
            }
        });

        snapDiagramToPixelButton.setText("Snap diagram to pixel");

        straightenLineButton.setText("Straighten line");

        saveRestoreButton.setText("Save Position");

        horizontalCenterAlignButton.setText("Horizontal Center Align");

        verticalCenterAlignButton.setText("Vertical Center Align");

        resetItemFlowButton.setText("Reset item flow");

        javax.swing.GroupLayout otherPanelLayout = new javax.swing.GroupLayout(otherPanel);
        otherPanel.setLayout(otherPanelLayout);
        otherPanelLayout.setHorizontalGroup(
            otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherPanelLayout.createSequentialGroup()
                        .addComponent(snapSelectedElementsToPixelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(snapDiagramToPixelButton))
                    .addGroup(otherPanelLayout.createSequentialGroup()
                        .addComponent(straightenLineButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveRestoreButton))
                    .addGroup(otherPanelLayout.createSequentialGroup()
                        .addComponent(horizontalCenterAlignButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verticalCenterAlignButton))
                    .addComponent(resetItemFlowButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        otherPanelLayout.setVerticalGroup(
            otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snapSelectedElementsToPixelButton)
                    .addComponent(snapDiagramToPixelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveRestoreButton)
                    .addComponent(straightenLineButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verticalCenterAlignButton)
                    .addComponent(horizontalCenterAlignButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetItemFlowButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        alignmentPanel.add(otherPanel);

        tabbedPanel.addTab("Alignment", alignmentPanel);

        valueNameLabel.setText("Name:");

        valueNameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueNameInputFieldActionPerformed(evt);
            }
        });

        valueTypeLabel.setText("Type:");

        createValueButton.setText("Create");

        javax.swing.GroupLayout fieldPanelLayout = new javax.swing.GroupLayout(fieldPanel);
        fieldPanel.setLayout(fieldPanelLayout);
        fieldPanelLayout.setHorizontalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fieldPanelLayout.createSequentialGroup()
                        .addComponent(valueNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueNameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fieldPanelLayout.createSequentialGroup()
                        .addComponent(valueTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valueTypeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createValueButton))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        fieldPanelLayout.setVerticalGroup(
            fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueNameLabel)
                    .addComponent(valueNameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueTypeLabel)
                    .addComponent(valueTypeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createValueButton)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Field", fieldPanel);

        timerLabel.setText("Timer (sec):");

        setTimerButton.setText("Set Timer");

        javax.swing.GroupLayout autosavePanelLayout = new javax.swing.GroupLayout(autosavePanel);
        autosavePanel.setLayout(autosavePanelLayout);
        autosavePanelLayout.setHorizontalGroup(
            autosavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autosavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autosavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(autosavePanelLayout.createSequentialGroup()
                        .addComponent(timerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timerInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setTimerButton))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        autosavePanelLayout.setVerticalGroup(
            autosavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autosavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autosavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timerLabel)
                    .addComponent(timerInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setTimerButton)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Autosave", autosavePanel);

        unmarshallInputButton.setText("Unmarshall input");

        unmarshallOutputButton.setText("Unmarshall output");

        splitObjectFlowButton.setText("Split object flow");

        javax.swing.GroupLayout activityPanelLayout = new javax.swing.GroupLayout(activityPanel);
        activityPanel.setLayout(activityPanelLayout);
        activityPanelLayout.setHorizontalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activityPanelLayout.createSequentialGroup()
                        .addComponent(unmarshallInputButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unmarshallOutputButton))
                    .addComponent(splitObjectFlowButton))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        activityPanelLayout.setVerticalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unmarshallInputButton)
                    .addComponent(unmarshallOutputButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitObjectFlowButton)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Activity", activityPanel);

        statisticsButton.setText("Show statistics");

        javax.swing.GroupLayout miscPanelLayout = new javax.swing.GroupLayout(miscPanel);
        miscPanel.setLayout(miscPanelLayout);
        miscPanelLayout.setHorizontalGroup(
            miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miscPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statisticsButton)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        miscPanelLayout.setVerticalGroup(
            miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miscPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statisticsButton)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Misc.", miscPanel);

        add(tabbedPanel, java.awt.BorderLayout.CENTER);
        tabbedPanel.getAccessibleContext().setAccessibleName("Location");
    }// </editor-fold>//GEN-END:initComponents

    private void valueNameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueNameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueNameInputFieldActionPerformed

    private void snapSelectedElementsToPixelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapSelectedElementsToPixelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snapSelectedElementsToPixelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activityPanel;
    private javax.swing.JPanel alignmentPanel;
    protected javax.swing.JButton applyButton;
    private javax.swing.JPanel autosavePanel;
    protected javax.swing.JButton createValueButton;
    private javax.swing.JPanel fieldPanel;
    protected javax.swing.JTextField heightInputField;
    private javax.swing.JLabel heightLabel;
    protected javax.swing.JButton horizontalCenterAlignButton;
    protected javax.swing.JTextField leftInputField;
    private javax.swing.JLabel leftLabel;
    private javax.swing.JPanel locationPanel;
    private javax.swing.JPanel miscPanel;
    private javax.swing.JPanel otherPanel;
    protected javax.swing.JButton resetItemFlowButton;
    protected javax.swing.JButton saveRestoreButton;
    protected javax.swing.JButton setTimerButton;
    protected javax.swing.JButton snapDiagramToPixelButton;
    protected javax.swing.JButton snapSelectedElementsToPixelButton;
    protected javax.swing.JButton splitObjectFlowButton;
    protected javax.swing.JButton statisticsButton;
    protected javax.swing.JButton straightenLineButton;
    private javax.swing.JTabbedPane tabbedPanel;
    protected javax.swing.JTextField timerInputField;
    private javax.swing.JLabel timerLabel;
    protected javax.swing.JTextField topInputField;
    private javax.swing.JLabel topLabel;
    protected javax.swing.JButton unmarshallInputButton;
    protected javax.swing.JButton unmarshallOutputButton;
    protected javax.swing.JTextField valueNameInputField;
    private javax.swing.JLabel valueNameLabel;
    protected javax.swing.JTextField valueTypeInputField;
    private javax.swing.JLabel valueTypeLabel;
    protected javax.swing.JButton verticalCenterAlignButton;
    protected javax.swing.JTextField widthInputField;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
}
